version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////data/egg_database.db
    volumes:
      - ./db:/data
    container_name: backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    container_name: frontend

  bot:
    build: ./bot
    environment:
      - TOKEN=ваш_токен_бота
      - DB_NAME=/data/egg_database.db
    volumes:
      - ./db:/data
    depends_on:
      - backend
    container_name: bot
